# Generated by Django 6.0.6 on 2026-06-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManage_app', '0003_remove_subject_student_subject_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='year',
            field=models.CharField(blank=True, choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], max_length=20, null=True),
        ),
    ]
