# Generated by Django 6.0.6 on 2026-06-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManage_app', '0005_subject_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='credits',
            field=models.IntegerField(default=3),
        ),
    ]
