# Generated by Django 6.0.6 on 2026-06-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManage_app', '0009_attendance_remarks_fee_due_date_fee_fee_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_teacher_admin',
            field=models.BooleanField(default=False, help_text='Can manage other teachers'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='password_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
