# Generated by Django 6.0.6 on 2026-06-29 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManage_app', '0014_remove_result_exam_date_alter_subject_subject_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['department__name', 'year', 'semester', 'subject_name']},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('department', 'subject_code')},
        ),
    ]
